SYSFILTER_MAJOR_VERSION=1
SYSFILTER_MINOR_VERSION=0
SYSFILTER_GIT_VERSION=$(shell git rev-parse --short HEAD 2>/dev/null || echo "nogit")

ifeq ($(SYSFILTER_GIT_VERSION),nogit)
	SYSFILTER_PATCH_VERSION=0
else
	SYSFILTER_PATCH_VERSION=$(SYSFILTER_GIT_VERSION)
endif

SYSFILTER_VERSION_FLAGS=\
	-DSYSFILTER_MAJOR_VERSION=$(SYSFILTER_MAJOR_VERSION) \
	-DSYSFILTER_MINOR_VERSION=$(SYSFILTER_MINOR_VERSION) \
	-DSYSFILTER_PATCH_VERSION=\"$(SYSFILTER_PATCH_VERSION)\" \
	-DSYSFILTER_VERSION_STRING=\"$(SYSFILTER_MAJOR_VERSION).$(SYSFILTER_MINOR_VERSION)-$(SYSFILTER_PATCH_VERSION)\"
